apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret  ## secret is used to store sensitive data like password, token, ssh key etc. in base64 encoded format
type: Opaque
data: 
  username: YWRtaW4= 
  password:  YWRtaW4xMjM=